### ISSUE TITLE
Problems archiving 'master' branch

### ISSUE THREAD

**Issue by vxbinaca** [gdamdam/iagitup#11]
`./iagitup.py -u https://github.com/soimort/you-get`

```
/home/vxbinaca/.iagitup/downloads/you-get soimort-you-get_-_2017-08-18_05-02-09
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error: rev-list died
Traceback (most recent call last):
  File "./iagitup.py", line 232, in <module>
    main()
  File "./iagitup.py", line 219, in main
    identifier, meta, bundle_filename= upload_ia(repo_folder, gh_repo_data, custom_meta=custom_meta_dict)
  File "./iagitup.py", line 156, in upload_ia
    bundle_file = create_bundle(gh_repo_folder, bundle_filename)
  File "./iagitup.py", line 107, in create_bundle
    subprocess.check_call(['git','bundle','create', bundle_name, 'master'])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'git', u'bundle', u'create', u'soimort-you-get_-_2017-08-18_05-02-09.bundle', u'master']' returned non-zero exit status 1
```

**Comment by gdamdam** [comment]
fixed in v1.2
