### ISSUE TITLE
Does not work in windows

### ISSUE THREAD

**Issue by soredake** [gdamdam/iagitup#21]
```
❯ iagitup https://github.com/Retera/WarsmashModEngine
:: Downloading https://github.com/Retera/WarsmashModEngine repository...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\user\.local\bin\iagitup.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\.local\pipx\venvs\iagitup\lib\site-packages\iagitup\__main__.py", line 56, in main
    gh_repo_data, repo_folder = iagitup.repo_download(URL)
  File "C:\Users\user\.local\pipx\venvs\iagitup\lib\site-packages\iagitup\iagitup.py", line 51, in repo_download
    shutil.rmtree(repo_folder)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user/.iagitup/downloads\\WarsmashModEngine\\.git\\objects\\pack\\pack-e2ffa04f0e8b508f2d32e1787a521cd873e94ed9.idx'
```

**Comment by PGSCOM** [comment]
Have you tried with administrator privileges?

**Comment by soredake** [comment]
@PGSCOM yes, still permission issue.
